import Link from 'next/link'

import { Control } from './Control'

import './globals.css'


export const metadata = {
  title: 'Web tutorial',
  description: 'Generated by egoing',
}

export default async function RootLayout({ children }) {

  const resp = await fetch('http://localhost:9999/topics/', {cache:'no-cache'})
  const topics = await resp.json()

  console.log('page/layout.js/topics', topics)

  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map(topic => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
          {/* <li><Link href='/read/1'>html</Link></li>
          <li><Link href='/read/2'>css</Link></li> */}
        </ol>
        {children}
        <Control/>
      </body>
      
    </html>
  )
}
